# Generated by Django 3.1.5 on 2021-01-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarim_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
